ceph_path_project: /home/vagrant/compose
ceph_path_volume: /home/vagrant/compose/vol
ceph_compose_template: docker-compose.yaml.jinja2
ceph_docker_config:
  COMPOSE_VERSION: 3
  CEPH_CONTAINER_VERSION: v3.1.0-stable-3.1-mimic-centos-7
  COMPOSE_NETWORK: cluster-net
  DASHBOARD_PORT: 8443
  DOCKER_NETWORK: ceph-cluster-net
  INTERNAL_DASHBOARD_PORT: 8443
  LANG: en_US.utf8
  MON1_IP: 172.18.0.2
  MON1_CEPH_PUBLIC_NETWORK: 172.18.0.0/16
  OSD_PATH: ./vol/osds
  PASSWORD: cephid
  RADOS_UID: radosid
  RADOS_PWD: radosid
  RADOS_DISPLAY: radosid
  RADOS_EMAIL: test@test.com
  RGW_PORT: 8080
  TZ: UTC
  USERNAME: cephid
  VOLUMES_PATH: ./vol/ceph

ceph_app_conf_EOF:
- osd pool default min size = 2
- max open files = 655350
- cephx cluster require signatures = false
- cephx service require signatures = false
- osd max object name len = 256
- osd max object namespace len = 64

ceph_dashboard_bootstrap:
- mon1 ceph mgr module enable dashboard
- mon1 ceph dashboard create-self-signed-cert
- mon1 ceph mgr module disable dashboard
- mon1 ceph mgr module enable dashboard
- mon1 ceph config set mgr mgr/dashboard/server_addr mgr
- mon1 ceph config set mgr mgr/dashboard/server_port 8443
- mon1 ceph dashboard set-login-credentials {{ ceph_docker_config.USERNAME }} {{ ceph_docker_config.PASSWORD }}

ceph_rados: mon1 radosgw-admin user create --uid="{{ ceph_docker_config.RADOS_UID }}" --display-name="{{ ceph_docker_config.RADOS_DISPLAY }}" --email="{{ ceph_docker_config.RADOS_EMAIL }}"
ceph_rados_info: mon1 radosgw-admin user info --uid={{ ceph_docker_config.RADOS_UID }}